### ISSUE TITLE
Unable to use it in Visual Studio

### ISSUE THREAD

**Issue by KastinArdnahc** [apertium/apertium-python#114]
Hello there,

I was trying to install it for isl - eng however, I encountered a lot of errors.
<img width="526" alt="Errors" src="https://github.com/apertium/apertium-python/assets/51816267/a21b8951-6455-478f-a164-758e494559f4">
Could you help me out?

p.s. I am using apertium 0.2.4

Thanks,
Kaustab

**Comment by TinoDidriksen** [comment]
Native Windows is not currently supported. Use WSL and the Ubuntu packages instead: https://wiki.apertium.org/wiki/Installation#Install_Apertium_Core_by_packaging.2Fvirtual_environment
