### ISSUE TITLE
Add py.typed

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-python#13]

**Comment by sushain97** [comment]
@Vaydheesh this should be an easy one if you're looking for something to do. In addition to adding it, it should be verified that importing `apertium` actually picks up the types.

**Comment by Vaydheesh** [comment]
Can I work on this after wrapping `apertium-destxt` and `cg-proc`

**Comment by sushain97** [comment]
Yeah, sure! `cg-proc` should be really easy since `hfst` already has Python wrappers.

**Comment by Vaydheesh** [comment]
> In addition to adding it, it should be verified that importing `apertium` actually picks up the types.

https://github.com/apertium/apertium-python/commit/bbe91ccd207ea20c39d74e1d63b755907228893b
How can I verify that py.typed is actually working?

**Comment by sushain97** [comment]
Try using the installed package in a normal Python file and see if mypy
picks up the types. There are ways to get mypy to reveal a type. You can
also intentionally create a type error and see what the return type is that
way (or bad argument type).
