### ISSUE TITLE
I am trying to check with Python but getting an error..

### ISSUE THREAD

**Issue by sridharbodla** [apertium/apertium-python#26]
![image](https://user-images.githubusercontent.com/2509305/42214755-0bdb229a-7eda-11e8-99eb-de3fb086c37f.png)

=> please suggest me how to use this module.

![image](https://user-images.githubusercontent.com/2509305/42215510-4da3239c-7edc-11e8-9769-6371fb57cff4.png)

Do i have to install any modules

**Comment by arghyatiger** [comment]
@sridharbodla  are you in the repository home when you're trying to import apertium?

**Comment by arghyatiger** [comment]
Also, you need to install the requirements.txt which has all the dependencies. Along with which you need to install the language specific data as well.

**Comment by arghyatiger** [comment]
```
wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
sudo apt-get -f --allow-unauthenticated install apertium-all-dev
sudo apt-get -f --allow-unauthenticated install apertium-es-en apertium-eng
```
Run this first and get all the apertium language-specific data and install apertium
then pip install the requirements.txt

**Comment by sridharbodla** [comment]
How to install this in windows?

**Comment by sushain97** [comment]
This is not ready for Windows usage.

See https://github.com/apertium/apertium-python/issues/6 for the issue which once closed, would indicate Windows support.
