### ISSUE TITLE
Analyzer code _get_commands() not processing first input.

### ISSUE THREAD

**Issue by arghyatiger** [apertium/apertium-python#32]
```
In [1]: import apertium

In [2]: a = apertium.Analyzer('en')

In [3]: a.analyze('cats')
Out[3]: []
```

But,

```
In [5]: a.analyze('hey cats')
Out[5]: [hey/hey<ij>]
```

This happens only for analysis. Generation doesn't have any such issues.

**Comment by arghyatiger** [comment]
INFO:

Happens when the command in mode file is passed.

Right now the pipeline uses  ```apertium``` command for analysis

**Comment by numan98khan** [comment]
I couldn't reproduce this bug. I am sorry but am I missing something? the above code gives me the results I want correctly.

**Comment by sushain97** [comment]
@Vaydheesh is this still a problem? I assume not. If not, can you close the issue.
