### ISSUE TITLE
Setup doc generation

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-python#4]
- [x] Sphinx
- [x] Readthedocs

**Comment by arghyatiger** [comment]
@sushain97 

https://github.com/apertium/apertium-python/tree/documentation


Tips for documentation?

**Comment by arghyatiger** [comment]
@sushain97  Alright, it isn't much I've written till now. So I'll change it to markdown.

Also, yes I did look into Streamparser docs, I'm trying to correct the docstring format so ```automodule``` and ```autoclass``` can work properly

**Comment by arghyatiger** [comment]
@sushain97  This task for GCI ?

**Comment by sushain97** [comment]
It's on the list.
