### ISSUE TITLE
Automatic installation of apt deps on Ubuntu setup.py

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-python#55]

**Comment by Vaydheesh** [comment]
will `apt-get install python3-lttoolbox` install its dependencies?

**Comment by sushain97** [comment]
Absolutely. Otherwise a package manager would be pretty useless. However, if the running Python doesn't match the distro Python, it won't work.

**Comment by Vaydheesh** [comment]
Can you add a description for this issue

**Comment by sushain97** [comment]
This issue is basically the `apt-get install python3-lttoolbox` stuff. Basically, `setup.py install`/`pip install` should install all the necessary deps.

**Comment by Vaydheesh** [comment]
Should I close this issue now, all the installation process is handled by `setup.py`

**Comment by sushain97** [comment]
Aren't we manually installing and building some wrappers?

**Comment by Vaydheesh** [comment]
Only `cg3` needs to be built, because the package isn't available.

**Comment by sushain97** [comment]
Fair enough.
