### ISSUE TITLE
Appveyor Apertium installation

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-python#6]
maybe through `setup.py install`? - Linux could piggyback off that too

**Comment by arghyatiger** [comment]
@sushain97  some idea on how I should proceed with this?
Also, for testing and implementation, a VM for windows should work?

**Comment by sushain97** [comment]
> VM for windows should work

Yea.

> some idea on how I should proceed with this?

I'm afraid not. Some googling is probably the best course of action. There are some links I've sent that are also related.

**Comment by arghyatiger** [comment]
Sure, I'll figure it out

**Comment by arghyatiger** [comment]
@sushain97  I've been able to make  ```lt-proc``` and other similar commands work on the windows command prompt.


But I encounter this error when I try to run the library


```
C:\Users\DELL\Documents\arghya_work\apertium-python-master\apertium-python-master>python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import apertium
>>> a = apertium.Analyzer('en')
>>> a.analyze('cats')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\DELL\Documents\arghya_work\apertium-python-master\apertium-python-master\apertium\analysis\__init__.py", line 37, in analyze
    result = execute(in_text, commands)
  File "C:\Users\DELL\Documents\arghya_work\apertium-python-master\apertium-python-master\apertium\utils.py", line 27, in execute
    subprocess.Popen(command, stdin=subprocess.PIPE, stdout=subprocess.PIPE),
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in _init_
    restore_signals, start_new_session)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
>>>
```
I'm working on this.
Do you by any chance have a hint of what might be going wrong?
subprocess module does exist

**Comment by sushain97** [comment]
That sounds like lt-proc isn't on the path when Python tries to execute it.

Is it?

**Comment by arghyatiger** [comment]
@sushain97 

```

In [3]:  g = apertium.Generator('en')

In [4]: g.generate('^cat<n><pl>$')
Error: Cannot not open file '/usr/share/apertium/apertium-eng/eng.autogen.bin'.

Out[4]: ''

In [5]:

In [5]: g.generator_cmds
Out[5]:
{'eng': [['lt-proc',
   '-z',
   '-g',
   '/usr/share/apertium/apertium-eng/eng.autogen.bin']]}

```

eng-gener.mode has this path given by default.
Ideas on how I should go about this?

**Comment by arghyatiger** [comment]
@sushain97 

```

In [1]: import apertium

In [2]:  g = apertium.Generator('en')

In [3]: g.generate('^cat<n><pl>$')
Out[3]: 'cats'
```

This are working finally. But the workaround seems really hacky. Theres a need to change the path in every .mode file.

Suggestions on how we can wrap the whole process and make it easier for people to use it?

**Comment by sushain97** [comment]
You can modify things that look like paths when you read mode files. How did you install the package? I would expect a proper Windows installation to also set the `.bin` path correctly.

**Comment by arghyatiger** [comment]
STEPS FOLLOWED:

0. Path for the apertium-python set to ```apertium-all-dev/share/apertium```
1. Download ```apertium-all-dev.zip```
2, Extract and set it's ```apertium-all-dev/bin``` folder to the path
3. Download ```.deb``` language data
4. Extract using ```7z```
5. Copy the contents to of language data to ```apertium-all-dev/share/apertium```
6. All ```.mode``` files need to be updated as their paths have ```/usr/share``` assumed

IDEA:
I was thinking if ```usr``` could be made a variable and replaced with ```apertium-all-dev/share``` ?

**Comment by sushain97** [comment]
Right, the `.deb` files are built in a particular way with that prefix. 

> All .mode files need to be updated as their paths have /usr/share assumed

We can't ask people to do this, unfortunately. That would make the install process unduly burdensome and confusing. It needs to be done automatically as a part of the extraction step or at time of `lt-proc` calls.

Also, we shouldn't make any assumptions about where the binaries are located, they should just be assumed to be on the path. Therefore, a Windows installation of this package should ensure they end up somewhere in the path or that we modify the system path to include it. I'm not sure what the standard is for Windows Python installs.

**Comment by arghyatiger** [comment]
@sushain97 
I'm writing a windows script that will download apertium-all-dev in the same repo and add it's bin to the PATH.

But there's a problem here as well.
There's something called the 7z which extracts .deb files in windows.
Now I don't know how I'm gonna install it from the script. Because I don't see a method for windows installation without a GUI.

thoughts?
Also, at this point what would be the best way to go about the method figured out to make things work on windows?

**Comment by sushain97** [comment]
> apertium-all-dev in the same repo

A real user wouldn't have a repo on their disk, they would have an installed package.

> 7z which extracts .deb files in windows

There are definitely ways to extract the file using Python. Googling something like 'extract deb Python` might be useful. Maybe Tino also packages them as a plain tar.gz or something?

> Also, at this point what would be the best way to go about the method figured out to make things work on windows?

I'm not sure what you're asking.

**Comment by arghyatiger** [comment]
Hi sushain,

Right now, the idea is if a user(like the one who reported an issue on
GitHub) clones the repo and tries to run Apertium+Python.They should be
able to.

And also get the appveyor test to pass.
That's why the script and everything.


Regards
Arghya Bhattacharya

**Comment by sushain97** [comment]
> Right now, the idea is if a user(like the one who reported an issue on
> GitHub) clones the repo and tries to run Apertium+Python.They should be
> able to.

This isn't a Windows installation though. The goal is to have this be pip-installable.

> And also get the appveyor test to pass.

Yes. As I said, this should be done via `setup.py install`.

**Comment by sridharbodla** [comment]
while i am trying with python jupyter notebook getting the below error.

![image](https://user-images.githubusercontent.com/2509305/43515651-ae010e2c-95a0-11e8-91db-fdd4ee214875.png)

**Comment by arghyatiger** [comment]
@sushain97 

How do you propose I should go about the .mode file modifications of the paths?

**Comment by arghyatiger** [comment]
@sridharbodla  This isn't ready for windows installation yet. Once this issue is closed you can try to run it and we'll figure out the problems you're having :)

**Comment by sushain97** [comment]
> How do you propose I should go about the .mode file modifications of the paths?

Detect things that look like paths and map them to corresponding file on the Windows filesystem based on where the mode file is located. You'll have to be a little intelligent about it.

**Comment by arghyatiger** [comment]
@sushain97  

```
In [1]: import apertium

In [2]: a = apertium.Analyzer("en")

In [3]: a.analyze("cats")
'apertium' is not recognized as an internal or external command,
operable program or batch file.
Out[3]: []

In [4]: g = apertium.Generator('en')

In [5]: g.generator_cmds
Out[5]: {}

In [6]: g.generate('^cat<n><pl>$')
Out[6]: 'cats'

In [7]: t = apertium.Translator("en", "es")

In [8]: t.translate("cats")
Out[8]: 'Gatos'
```
For analysis, I tried the ```lt-proc``` command directly but that has some postprocessing issues that I couldn't figure out.
I've created an issue for it.

**Comment by arghyatiger** [comment]
@sridharbodla could you try cloning the ```windows``` branch and run Apertium+Python with the instructions in readme?
