### ISSUE TITLE
Support tagger modes via new Tagger object

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-python#61]
@ftyers thinks this is the most important right now

**Comment by Vaydheesh** [comment]
By `tagger modes` do you mean https://github.com/apertium/apertium-eng/blob/master/modes.xml#L20

`apertium.Tagger('en')` should return output of above pipeline?

**Comment by sushain97** [comment]
Yes.

**Comment by sushain97** [comment]
Nice work!
