### ISSUE TITLE
Get this ready for pip release

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-python#66]
```
# TODO: Add version description, keywords, author, author_email
```

^ Needs to happen. They should be via dunder methods on the module.

`setup.py` targets for these would be nice:

https://github.com/apertium/apertium-init/blob/master/Makefile#L14-L23

**Comment by Vaydheesh** [comment]
> `setup.py` targets for these would be nice:

Should I create a `Makefile` for this?

**Comment by sushain97** [comment]
If we can do something in Python, that would be great. If not, `Makefile` works OK.
