### ISSUE TITLE
Bundle apertium-lex-tools with apertium

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium-python#70]
It would be good if we could just bundle all the apertium-* together in a single package, e.g. -separable, -lex-tools, -anaphora etc.

**Comment by Vaydheesh** [comment]
according to `control` https://apertium.projectjj.com/apt/nightly/pool/main/a/apertium/apertium-all-dev_3.5.2+g734~6f70c46d-1~xenial1_all.deb
```
Depends: apertium-dev (>= 3.5.2+g734~6f70c46d-1~xenial1), apertium-eval-translator, apertium-lex-tools (>= 0.2.1), apertium-separable (>= 0.3.2), autoconf, automake, build-essential, cg3 (>=
1.1.6), gawk, git, hfst (>= 3.14.0), libcg3-dev (>= 1.1.6), libhfst-dev (>= 3.14.0), libtool, locales, pkg-config, subversion
```
`apertium-separable` and `apertium-lex-tools` should be installed with `apertium-all-dev`
