### ISSUE TITLE
Set up CI to make sure it works on Windows

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium-python#85]

**Comment by sushain97** [comment]
We have windows CI already: https://ci.appveyor.com/project/sushain97/apertium-python/builds/35271599

**Comment by sushain97** [comment]
(it's existed since this repo was first created)

**Comment by ftyers** [comment]
Hmm, but it doesn't test that modules work ?

**Comment by sushain97** [comment]
It does.

This just sounds like a bug! Would need more information to see what went wrong.

**Comment by sushain97** [comment]
Hmm maybe it's related to some of the skipped tests on windows here: https://github.com/apertium/apertium-python/blob/master/tests/__init__.py#L127-L147

**Comment by TinoDidriksen** [comment]
Some binaries are available: https://apertium.projectjj.com/win32/nightly/ file `apertium-all-dev.7z` or `.zip`
I still haven't gotten around to cross-building a few of the tools for Windows because WSL has served so nicely, but I can set up the last ones.

**Comment by ftyers** [comment]
It's more the language packages it seems?

**Comment by TinoDidriksen** [comment]
Languages are all available, listed in https://apertium.projectjj.com/pkgs.php - the `.deb` files can be extracted with 7-zip or `ar` + `tar -Jx`

**Comment by ftyers** [comment]
Can it be done by novice users? Wouldn't it be better to have a less onerous method to use this?

**Comment by TinoDidriksen** [comment]
The native and Java frontends do it for users. The Python frontend can also do the same.

**Comment by Vaydheesh** [comment]
There is a bug in existing python installer. The `taggers` and other variables aren't updated upon installation of new modules https://github.com/apertium/apertium-python/blob/master/apertium/__init__.py#L82. 

However launching a new interpreter should fix this issue.

 I'll create a PR to remove this bug
